# Generated by Django 3.2.5 on 2021-08-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210819_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
